### ISSUE TITLE
z3 throwing error with complex conditions

### ISSUE THREAD

**Issue by mayanksolanki393** [CS639A-PAVT/BugTracker#12]
**Describe the bug**
On using the "AND" condition in the turtle program. z3 is throwing an error.

**To Reproduce**
- Provide the turtle program
```
if (:c1 > 30 && :c1 < 50) [
    :y = :x
]
```
- command I am using to run the program
```
python kachua.py -t 100 -se <path-turtle> -c '{":c1": 1}' -d '{":x": 1, ":y": 1}'
```

**Screenshots**
Stack Trace:
```
setAttr <sExecutionInterface.z3Context object at 0x0486AA90> x x
setAttr <sExecutionInterface.z3Context object at 0x0486AA90> y y
setAttr <sExecutionInterface.z3Context object at 0x0486AA90> c1 c1
Traceback (most recent call last):
  File "kachua.py", line 107, in <module>
    cov, corpus = se.symbolicExecutionMain(ir, args.params, args.constparams, timeLimit=args.timeout)
  File "C:\Users\Mayank\Desktop\Program AVT\Assignments\Assignment_5_v1\assignment_5_21111414\KachuaCore\sExecution.py", line 121, in symbolicExecutionMain
    encPC = s.handleCondition(stmt,not pcEval[pcIndex])
  File "C:\Users\Mayank\Desktop\Program AVT\Assignments\Assignment_5_v1\assignment_5_21111414\KachuaCore\sExecutionInterface.py", line 87, in handleCondition
    exec("exp = %s"%(temp),globals(),_locals)
  File "<string>", line 1, in <module>
  File "C:\Users\Mayank\AppData\Local\Programs\Python\Python38-32\lib\site-packages\z3\z3.py", line 380, in __bool__
    raise Z3Exception("Symbolic expressions cannot be cast to concrete Boolean values.")
z3.z3types.Z3Exception: Symbolic expressions cannot be cast to concrete Boolean values.
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python3 version: Python 3.8.5

**Comment by mayanksolanki393** [comment]
FYI, a possible workaround for now is to restructure the turtle program like this
```
if (:c1 > 30) [
    if (:c1 < 50) [
        :y = :x
    ] 
]
```
